"""
PDF Report Generator
Produces a formatted executive PDF report from agent outputs.
"""

import os
import re
from datetime import datetime
from fpdf import FPDF


class StrategyReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_fill_color(30, 58, 138)   # deep blue
        self.set_text_color(255, 255, 255)
        self.rect(0, 0, 210, 18, "F")
        self.set_xy(0, 3)
        self.cell(0, 12, "AI-Powered Product Strategy Report", align="C")
        self.set_text_color(0, 0, 0)
        self.ln(14)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Generated by Product Strategy Assistant  |  Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(219, 234, 254)  # light blue
        self.set_text_color(30, 58, 138)
        self.cell(0, 9, f"  {title}", ln=True, fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(30, 30, 30)
        # Clean non-latin characters that fpdf can't encode
        safe_text = text.encode("latin-1", errors="replace").decode("latin-1")
        self.multi_cell(0, 6, safe_text)
        self.ln(2)

    def meta_line(self, label: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(80, 80, 80)
        self.cell(35, 6, label + ":", ln=False)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 6, value, ln=True)
        self.set_text_color(0, 0, 0)


def _clean(text: str) -> str:
    """Strip markdown bold/italic markers for PDF body."""
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    text = re.sub(r"#{1,6}\s*", "", text)
    return text.strip()


def generate_pdf_report(agent_outputs: dict, output_path: str = None) -> str:
    """
    Generate a PDF executive report from agent outputs dict.
    agent_outputs keys: customer_feedback, market_research, competitor_analysis,
                        swot_analysis, feature_prioritization, strategy_recommendations,
                        executive_summary
    Returns path to generated PDF.
    """
    if output_path is None:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        reports_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "reports")
        os.makedirs(reports_dir, exist_ok=True)
        output_path = os.path.join(reports_dir, f"strategy_report_{ts}.pdf")

    pdf = StrategyReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Cover metadata ────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(30, 58, 138)
    pdf.ln(4)
    pdf.cell(0, 12, "Product Strategy Executive Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, f"Generated on: {datetime.now().strftime('%B %d, %Y  %H:%M')}", ln=True, align="C")
    pdf.ln(6)
    pdf.set_draw_color(30, 58, 138)
    pdf.set_line_width(0.5)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(6)

    # ── Table of contents (static) ─────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 7, "Contents", ln=True)
    sections = [
        "1. Executive Summary",
        "2. Customer Feedback Analysis",
        "3. Market Research Summary",
        "4. Competitor Analysis",
        "5. SWOT Analysis",
        "6. Feature Prioritization",
        "7. Strategic Recommendations",
    ]
    pdf.set_font("Helvetica", "", 10)
    for s in sections:
        pdf.cell(0, 6, f"   {s}", ln=True)
    pdf.ln(4)

    section_map = [
        ("1. Executive Summary",          "executive_summary"),
        ("2. Customer Feedback Analysis",  "customer_feedback"),
        ("3. Market Research Summary",     "market_research"),
        ("4. Competitor Analysis",         "competitor_analysis"),
        ("5. SWOT Analysis",               "swot_analysis"),
        ("6. Feature Prioritization",      "feature_prioritization"),
        ("7. Strategic Recommendations",   "strategy_recommendations"),
    ]

    for title, key in section_map:
        content = agent_outputs.get(key, "")
        if not content:
            continue
        pdf.section_title(title)
        pdf.body_text(_clean(content))

    pdf.output(output_path)
    return output_path
